[build]
  command = "npm run build"
  publish = "dist/manage-birthday/browser"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Add this redirect rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
